#! /usr/bin/python
import math, random

names = [
    "James","Mary","John","Patricia","Robert","Jennifer","Michael","Elizabeth","William","Linda","David","Barbara","Richard","Susan","Joseph","Jessica","Thomas","Margaret","Charles","Sarah","Christopher","Karen","Daniel","Nancy","Matthew","Betty","Anthony","Lisa","Donald","Dorothy","Mark","Sandra","Paul","Ashley","Steven","Kimberly","Andrew","Donna","Kenneth","Carol","George","Michelle","Joshua","Emily","Kevin","Amanda","Brian","Helen","Edward","Melissa","Ronald","Deborah","Timothy","Stephanie","Jason","Laura","Jeffrey","Rebecca","Ryan","Sharon","Gary","Cynthia","Jacob","Kathleen","Nicholas","Amy","Eric","Shirley","Stephen","Anna","Jonathan","Angela","Larry","Ruth","Justin","Brenda","Scott","Pamela","Frank","Nicole","Brandon","Katherine","Raymond","Virginia","Gregory","Catherine","Benjamin","Christine","Samuel","Samantha","Patrick","Debra","Alexander","Janet","Jack","Rachel","Dennis","Carolyn","Jerry","Emma","Tyler","Maria","Aaron","Heather","Henry","Diane","Douglas","Julie","Jose","Joyce","Peter","Evelyn","Adam","Frances","Zachary","Joan","Nathan","Christina","Walter","Kelly","Harold","Victoria","Kyle","Lauren","Carl","Martha","Arthur","Judith","Gerald","Cheryl","Roger","Megan","Keith","Andrea","Jeremy","Ann","Terry","Alice","Lawrence","Jean","Sean","Doris","Christian","Jacqueline","Albert","Kathryn","Joe","Hannah","Ethan","Olivia","Austin","Gloria","Jesse","Marie","Willie","Teresa","Billy","Sara","Bryan","Janice","Bruce","Julia","Jordan","Grace","Ralph","Judy","Roy","Theresa","Noah","Rose","Dylan","Beverly","Eugene","Denise","Wayne","Marilyn","Alan","Amber","Juan","Madison","Louis","Danielle","Russell","Brittany","Gabriel","Diana","Randy","Abigail","Philip","Jane","Harry","Natalie","Vincent","Lori","Bobby","Tiffany","Johnny","Alexis","Logan","Kayla"
]

surnames = [
    "Smith","Johnson","Williams","Jones","Brown","Davis","Miller","Wilson","Moore","Taylor","Anderson","Thomas","Jackson","White","Harris","Martin","Thompson","Garcia","Martinez","Robinson","Clark","Rodriguez","Lewis","Lee","Walker","Hall","Allen","Young","Hernandez","King","Wright","Lopez","Hill","Scott","Green","Adams","Baker","Gonzalez","Nelson","Carter","Mitchell","Perez","Roberts","Turner","Phillips","Campbell","Parker","Evans","Edwards","Collins","Stewart","Sanchez","Morris","Rogers","Reed","Cook","Morgan","Bell","Murphy","Bailey","Rivera","Cooper","Richardson","Cox","Howard","Ward","Torres","Peterson","Gray","Ramirez","James","Watson","Brooks","Kelly","Sanders","Price","Bennett","Wood","Barnes","Ross","Henderson","Coleman","Jenkins","Perry","Powell","Long","Patterson","Hughes","Flores","Washington","Butler","Simmons","Foster","Gonzales","Bryant","Alexander","Russell","Griffin","Diaz","Hayes","Myers","Ford","Hamilton","Graham","Sullivan","Wallace","Woods","Cole","West","Jordan","Owens","Reynolds","Fisher","Ellis","Harrison","Gibson","Mcdonald","Cruz","Marshall","Ortiz","Gomez","Murray","Freeman","Wells","Webb","Simpson","Stevens","Tucker","Porter","Hunter","Hicks","Crawford","Henry","Boyd","Mason","Morales","Kennedy","Warren","Dixon","Ramos","Reyes","Burns","Gordon","Shaw","Holmes","Rice","Robertson","Hunt","Black","Daniels","Palmer","Mills","Nichols","Grant","Knight","Ferguson","Rose","Stone","Hawkins","Dunn","Perkins","Hudson","Spencer","Gardner","Stephens","Payne","Pierce","Berry","Matthews","Arnold","Wagner","Willis","Ray","Watkins","Olson","Carroll","Duncan","Snyder","Hart","Cunningham","Bradley","Lane","Andrews","Ruiz","Harper","Fox","Riley","Armstrong","Carpenter","Weaver","Greene","Lawrence","Elliott","Chavez","Sims","Austin","Peters","Kelley","Franklin","Lawson","Fields","Gutierrez","Ryan","Schmidt","Carr","Vasquez","Castillo","Wheeler","Chapman","Oliver","Montgomery","Richards","Williamson","Johnston","Banks","Meyer","Bishop","Mccoy","Howell","Alvarez","Morrison","Hansen","Fernandez","Garza","Harvey","Little","Burton","Stanley","Nguyen","George","Jacobs","Reid","Kim","Fuller","Lynch","Dean","Gilbert","Garrett","Romero","Welch","Larson","Frazier","Burke","Hanson","Day","Mendoza","Moreno","Bowman","Medina","Fowler"
]

for i in range(1,1000):
    forename = random.choice(names)
    surname = random.choice(surnames)
    name = forename +" "+ surname
    phone = random.randint(600000000,700000000)

    print "%d;%s;%d"% (i, name, phone)
